config/routes.rb
TwitterSearch::Application.routes.draw do
  resources :trends do
    match 'results' => 'results#show'
  end

  root :to => 'trends#index'
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :trend
  
  def self.create_from_tweet(twitter_result)
    create(:result => twitter_result["text"], :user_name => twitter_result["from_user"])
  end
end

app/models/trend.rb
class Trend < ActiveRecord::Base
  include HTTParty
  
  has_many :results
  validates :query, :presence => true
  
  def self.create_and_search(params)
    trend = Trend.new(params)
    twitter_response = get("http://search.twitter.com/search.json?q=#{URI.escape params[:query]}&rpp=10")
    if trend.save
      trend.call_parse_reponse(twitter_response)
    else
      false
    end
  end
  
  def call_parse_reponse(response)
    parse_response(response)
  end
  
  private

  def parse_response(response)
    if response["results"]
      response["results"].each do |twitter_result|
        results.create_from_tweet(twitter_result)
      end
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  
  def show
    @results = trend.results
  end
  
  private
  
  def trend
    @trend ||= Trend.find_by_id(params[:trend_id])
  end
  
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController

  def index
    @trends = Trend.all
    @trend = Trend.new

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def create
    respond_to do |format|
      if Trend.create_and_search(params[:trend])
        format.html { redirect_to root_url, notice: 'Trend was successfully created.' }
      else
        format.html { redirect_to root_url, error: 'Sorry, there was a problem saving the trend. Please try again'}
      end
    end
  end

  def destroy
    trend = Trend.find(params[:id])
    trend.destroy

    respond_to do |format|
      format.html { redirect_to trends_url, notice: 'Destroy was successful.' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterSearch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/results/show.html.erb
<h2>Trend results for <%= @trend.query%> </h2>
<%= link_to "Back", trends_path %>
<div class="results">
    <ul>
  <% @results.each do |result| %>
      <li>
        <p><div><strong><%= result.user_name.to_s %></strong></div>
        <div><%= result.result %></div></p>
      </li>
  <% end %>
    <ul>
</div>

app/views/trends/_form.html.erb
<%= form_for(@trend) do |f| %>
  <% if @trend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trend.errors.count, "error") %> prohibited this trend from being saved:</h2>

      <ul>
      <% @trend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :query %><br />
    <%= f.text_field :query %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trends/index.html.erb
<h1>Listing trends</h1>
<p>
  <%= form_for @trend do |f| %>
    <% if @trend.errors.any? %>
      <div id="errorExplanation">
        <% @trend.errors.full_messages.each do |msg| %>  
          <li><%= msg %></li>  
        <% end %>
    </div>
    <% end %>
    <%= f.search_field :query %><%= submit_tag "search twitter" %>
  <% end %>
</p>
<table>
  <tr>
    <th>Search term</th>
    <th>Searched on</th>
    <th></th>
    <th></th>
  </tr>
<% @trends.each do |trend| %>
  <tr>
    <td><%= link_to trend.query, trend_results_path(trend) unless trend.results.blank? %> and found <%= pluralize trend.results.count, "response" %> </td>
    <td><%= trend.created_at.strftime("on %c ")%></td>
    <td></td>
    <td><%= link_to 'Destroy', trend, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<p>
  <%= "No search results yet." unless @trends.any? %>
</p>